"use client";

import React from "react";
import { motion } from "framer-motion";
import {
    Plane,
    Wallet,
    Users,
    Sparkles,
    ArrowUpRight,
    ArrowDownLeft,
    Layers,
} from "lucide-react";

interface OverviewCardsProps {
    stats?: {
        totalTrips: number;
        upcomingTrips: number;
        totalExpenses: number;
        moneyOwed: number;
        moneyReceivable: number;
        savedItineraries: number;
        friendsCount: number;
    };
}

function formatAmount(amount: number) {
    try {
        return new Intl.NumberFormat("en-IN", {
            style: "currency",
            currency: "INR",
            maximumFractionDigits: 0,
        }).format(amount);
    } catch {
        return `INR ${amount}`;
    }
}

export function OverviewCards({ stats }: OverviewCardsProps) {
    const data = stats || {
        totalTrips: 0,
        upcomingTrips: 0,
        totalExpenses: 0,
        moneyOwed: 0,
        moneyReceivable: 0,
        savedItineraries: 0,
        friendsCount: 0,
    };

    const CARDS = [
        {
            title: "Total Trips",
            value: data.totalTrips.toString(),
            description: `${data.friendsCount} travel companions`,
            icon: Layers,
            iconColor: "text-blue-500",
            bgColor: "bg-blue-500/10",
        },
        {
            title: "Upcoming Trips",
            value: data.upcomingTrips.toString(),
            description: "Timeline planning active",
            icon: Plane,
            iconColor: "text-cyan-500",
            bgColor: "bg-cyan-500/10",
        },
        {
            title: "Total Expenses",
            value: formatAmount(data.totalExpenses),
            description: "Across all active trips",
            icon: Wallet,
            iconColor: "text-emerald-500",
            bgColor: "bg-emerald-500/10",
        },
        {
            title: "Money You Owe",
            value: formatAmount(data.moneyOwed),
            description: "Unsettled balances",
            icon: ArrowDownLeft,
            iconColor: "text-rose-500",
            bgColor: "bg-rose-500/10",
        },
        {
            title: "Money You'll Receive",
            value: formatAmount(data.moneyReceivable),
            description: "Pending collection",
            icon: ArrowUpRight,
            iconColor: "text-amber-500",
            bgColor: "bg-amber-500/10",
        },
        {
            title: "Saved AI Itineraries",
            value: data.savedItineraries.toString(),
            description: "Generated by Gemini",
            icon: Sparkles,
            iconColor: "text-primary",
            bgColor: "bg-primary/10",
        },
    ];

    const containerVariants = {
        hidden: {},
        visible: {
            transition: {
                staggerChildren: 0.05,
            },
        },
    };

    const cardVariants = {
        hidden: { opacity: 0, y: 12 },
        visible: { 
            opacity: 1, 
            y: 0,
            transition: { type: "spring" as const, stiffness: 260, damping: 20 }
        },
    };

    return (
        <motion.section 
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="grid gap-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"
        >
            {CARDS.map((item) => (
                <motion.div
                    key={item.title}
                    variants={cardVariants}
                    whileHover={{ y: -3, transition: { duration: 0.15 } }}
                    className="rounded-xl border border-border bg-card p-5 shadow-sm hover:shadow-md transition-shadow flex flex-col justify-between cursor-default min-h-[135px]"
                >
                    <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0">
                            <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">
                                {item.title}
                            </p>

                            <h3 className="mt-2 text-xl font-extrabold text-foreground truncate">
                                {item.value}
                            </h3>
                        </div>

                        <div className={`rounded-lg p-2 shrink-0 ${item.bgColor}`}>
                            <item.icon className={`h-4.5 w-4.5 ${item.iconColor}`} />
                        </div>
                    </div>

                    <p className="mt-3 text-[11px] text-muted-foreground truncate font-medium">
                        {item.description}
                    </p>
                </motion.div>
            ))}
        </motion.section>
    );
}